### ISSUE TITLE
Some source files are missing Apache license headers

### ISSUE THREAD

**Issue by daisy-ycguo** [apache/incubator-openwhisk-wskdeploy#716]
In order to compliance with Apache release policy, every artifact distributed MUST contain appropriately licensed code. I used Apache Rat to check this repository and find below files miss license headers. So we need to add Apache licensing header to those files. 

```
Unapproved licenses:

  ./.travis.yml
  ./DEPENDENCIES.md
  ./Dockerfile
  ./Makefile
  ./build.sh
  ./ansible/environments/local/hosts
  ./ansible/environments/local/group_vars/all
  ./docs/creating_tagged_releases.md
  ./docs/programming_guide.md
  ./docs/wskdeploy_action_advanced_parms.md
  ./docs/wskdeploy_action_env_var_parms.md
  ./docs/wskdeploy_action_fixed_parms.md
  ./docs/wskdeploy_action_helloworld.md
  ./docs/wskdeploy_action_runtime.md
  ./docs/wskdeploy_action_typed_parms.md
  ./docs/wskdeploy_configuring.md
  ./docs/wskdeploy_debugging.md
  ./docs/wskdeploy_example_template.md
  ./docs/wskdeploy_faq.md
  ./docs/wskdeploy_package_minimal.md
  ./docs/wskdeploy_sequence_basic.md
  ./docs/wskdeploy_triggerrule_basic.md
  ./docs/wskdeploy_triggerrule_trigger_bindings.md
  ./docs/examples/deployment_hello_world_triggerrule_bindings.yaml
  ./docs/examples/deployment_hello_world_triggerrule_unbound.yaml
  ./docs/examples/manifest_hello_world.yaml
  ./docs/examples/manifest_hello_world_advanced_parms.yaml
  ./docs/examples/manifest_hello_world_env_var_parms.yaml
  ./docs/examples/manifest_hello_world_fixed_parms.yaml
  ./docs/examples/manifest_hello_world_runtime.yaml
  ./docs/examples/manifest_hello_world_triggerrule.yaml
  ./docs/examples/manifest_hello_world_triggerrule_unbound.yaml
  ./docs/examples/manifest_hello_world_typed_parms.yaml
  ./docs/examples/manifest_package_minimal.yaml
  ./docs/examples/manifest_sequence_basic.yaml
  ./docs/examples/src/hello.js
  ./docs/examples/src/hello.py
  ./docs/examples/src/hello_plus.js
  ./docs/examples/src/member_equip.js
  ./docs/examples/src/member_join.js
  ./docs/examples/src/member_process.js
  ./gradle/wrapper/gradle-wrapper.properties
  ./specification/diagrams/README.md
  ./specification/html/spec_actions.md
  ./specification/html/spec_index.md
  ./specification/html/spec_normative_refs.md
  ./specification/html/spec_packages.md
  ./specification/html/spec_parameters.md
  ./specification/html/spec_sequences.md
  ./specification/html/spec_shared_entity_schema.md
  ./specification/html/spec_trigger_rule.md
  ./specification/html/spec_types.md
  ./specification/images/images.md
  ./tests/README.md
  ./tests/apps/openwhisk-githubslackbot/README.md
  ./tests/apps/openwhisk-githubslackbot/manifest.yaml
  ./tests/apps/owbp-cloudant-trigger/README.md
  ./tests/apps/owbp-cloudant-trigger/runtimes/node/manifest.yaml
  ./tests/apps/owbp-cloudant-trigger/runtimes/node/actions/process-change.js
  ./tests/apps/owbp-cloudant-trigger/runtimes/php/manifest.yaml
  ./tests/apps/owbp-cloudant-trigger/runtimes/php/actions/process-change.php
  ./tests/apps/owbp-cloudant-trigger/runtimes/python/manifest.yaml
  ./tests/apps/owbp-cloudant-trigger/runtimes/python/actions/process-change.py
  ./tests/apps/owbp-cloudant-trigger/runtimes/swift/manifest.yaml
  ./tests/apps/owbp-cloudant-trigger/runtimes/swift/actions/process-change.swift
  ./tests/dat/deployment-deploymentreader-test-package.yml
  ./tests/dat/deployment-deploymentreader-test-packages.yml
  ./tests/dat/deployment-deploymentreader-test.yml
  ./tests/dat/deployment_compose_trigger.yaml
  ./tests/dat/deployment_data_action_with_inputs_outputs.yaml
  ./tests/dat/deployment_data_package.yaml
  ./tests/dat/deployment_data_package_env_var.yaml
  ./tests/dat/deployment_data_packages.yaml
  ./tests/dat/deployment_data_packages_env_var.yaml
  ./tests/dat/deployment_data_project.yaml
  ./tests/dat/deployment_data_project_package.yaml
  ./tests/dat/deployment_data_project_package_env_var.yaml
  ./tests/dat/deployment_data_project_package_env_var_con.yaml
  ./tests/dat/deployment_data_project_packages_env_var.yaml
  ./tests/dat/deployment_data_project_packages_env_var_con.yaml
  ./tests/dat/deployment_validate_action_annotations.yaml
  ./tests/dat/deployment_validate_credentials.yaml
  ./tests/dat/deployment_validate_deployment_reader.yaml
  ./tests/dat/manifest_bad_yaml_invalid_comment.yaml
  ./tests/dat/manifest_bad_yaml_invalid_key_mapping_value.yaml
  ./tests/dat/manifest_bad_yaml_invalid_package_key.yaml
  ./tests/dat/manifest_bad_yaml_missing_root_key.yaml
  ./tests/dat/manifest_data_compose_triggers.yaml
  ./tests/dat/manifest_data_rule_env_var.yaml
  ./tests/dat/manifest_hello_java_jar.yaml
  ./tests/dat/manifest_hello_nodejs.yaml
  ./tests/dat/manifest_hello_nodejs_with_params.yaml
  ./tests/dat/manifest_hello_python.yaml
  ./tests/dat/manifest_hello_swift.yaml
  ./tests/dat/manifest_invalid_package_missing.yaml
  ./tests/dat/manifest_validate_action_annotations.yaml
  ./tests/dat/manifest_validate_credentials.yaml
  ./tests/dat/manifest_validate_deployment_reader.yaml
  ./tests/dat/manifest_validate_feed.yaml
  ./tests/dat/manifest_validate_json_params.yaml
  ./tests/dat/manifest_validate_multiline_params.yaml
  ./tests/dat/manifest_validate_package_grammar.yaml
  ./tests/dat/manifest_validate_package_grammar_env_var.yaml
  ./tests/dat/manifest_validate_params.yaml
  ./tests/dat/manifest_validate_rule.yaml
  ./tests/dat/manifest_validate_singleline_params.yaml
  ./tests/dat/manifest_validate_trigger_action_rule_grammar.yaml
  ./tests/dat/manifest_validate_triggerfeed.yaml
  ./tests/dat/wskprops
  ./tests/dat/wskpropsnokeycert
  ./tests/dat/actions/dump_params.js
  ./tests/dat/actions/hello.js
  ./tests/src/integration/alarmtrigger/README.md
  ./tests/src/integration/alarmtrigger/deployment.yaml
  ./tests/src/integration/alarmtrigger/manifest.yaml
  ./tests/src/integration/alarmtrigger/actions/hello.js
  ./tests/src/integration/apigateway/manifest.yml
  ./tests/src/integration/apigateway/src/greeting.js
  ./tests/src/integration/cloudant/README.md
  ./tests/src/integration/cloudant/manifest.yaml
  ./tests/src/integration/dependency/README.md
  ./tests/src/integration/dependency/manifest.yaml
  ./tests/src/integration/flagstests/deployment.yml
  ./tests/src/integration/flagstests/manifest.yaml
  ./tests/src/integration/flagstests/manifest.yml
  ./tests/src/integration/flagstests/src/greeting.js
  ./tests/src/integration/helloworld/README.md
  ./tests/src/integration/helloworld/deployment.yaml
  ./tests/src/integration/helloworld/manifest.yaml
  ./tests/src/integration/jaraction/manifest.yaml
  ./tests/src/integration/managed-deployment/00-manifest-minus-second-package.yaml
  ./tests/src/integration/managed-deployment/01-manifest-minus-sequence-2.yaml
  ./tests/src/integration/managed-deployment/02-manifest-minus-action-3.yaml
  ./tests/src/integration/managed-deployment/03-manifest-minus-trigger.yaml
  ./tests/src/integration/managed-deployment/04-manifest-minus-package.yaml
  ./tests/src/integration/managed-deployment/manifest.yaml
  ./tests/src/integration/message-hub/README.md
  ./tests/src/integration/message-hub/deployment.yaml
  ./tests/src/integration/message-hub/manifest.yaml
  ./tests/src/integration/message-hub/src/process-messages.js
  ./tests/src/integration/message-hub/src/receive-messages.js
  ./tests/src/integration/runtimetests/manifest.yaml
  ./tests/src/integration/runtimetests/src/greeting.js
  ./tests/src/integration/runtimetests/src/hello.php
  ./tests/src/integration/runtimetests/src/hello.py
  ./tests/src/integration/runtimetests/src/hello.swift
  ./tests/src/integration/runtimetests/src/helloworld/index.js
  ./tests/src/integration/runtimetests/src/helloworld/node_modules/string-format/README.md
  ./tests/src/integration/runtimetests/src/helloworld/node_modules/string-format/lib/string-format.js
  ./tests/src/integration/triggerrule/deployment.yml
  ./tests/src/integration/triggerrule/manifest.yml
  ./tests/src/integration/triggerrule/src/greeting.js
  ./tests/src/integration/validate-action-annotations/deployment-with-invalid-annotations.yaml
  ./tests/src/integration/validate-action-annotations/deployment.yaml
  ./tests/src/integration/validate-action-annotations/manifest.yaml
  ./tests/src/integration/validate-application-and-project/deployment-with-application.yaml
  ./tests/src/integration/validate-application-and-project/deployment-with-project.yaml
  ./tests/src/integration/validate-application-and-project/manifest-with-application.yaml
  ./tests/src/integration/validate-application-and-project/manifest-with-project.yaml
  ./tests/src/integration/validate-binding-inputs-annotations/deployment.yaml
  ./tests/src/integration/validate-binding-inputs-annotations/manifest.yaml
  ./tests/src/integration/validate-binding-inputs-annotations/actions/helloworld.js
  ./tests/src/integration/validate-manifest-deployment-file-extensions/deployment.yaml
  ./tests/src/integration/validate-manifest-deployment-file-extensions/deployment.yml
  ./tests/src/integration/validate-manifest-deployment-file-extensions/manifest.yaml
  ./tests/src/integration/validate-manifest-deployment-file-extensions/manifest.yml
  ./tests/src/integration/validate-manifest-deployment-file-extensions/not-standard-deployment.yaml
  ./tests/src/integration/validate-manifest-deployment-file-extensions/not-standard-manifest.yaml
  ./tests/src/integration/validate-manifest-deployment-file-extensions/random-name-1.yaml
  ./tests/src/integration/validate-manifest-deployment-file-extensions/random-name-2.yaml
  ./tests/src/integration/validate-manifest-deployment-file-extensions/yaml-deployment-with-yml-manifest.yaml
  ./tests/src/integration/validate-manifest-deployment-file-extensions/yaml-manifest-with-yml-deployment.yaml
  ./tests/src/integration/validate-manifest-deployment-file-extensions/yml-deployment-with-yaml-manifest.yml
  ./tests/src/integration/validate-manifest-deployment-file-extensions/yml-manifest-with-yaml-deployment.yml
  ./tests/src/integration/validate-package-in-manifest/deployment.yaml
  ./tests/src/integration/validate-package-in-manifest/manifest.yaml
  ./tests/src/integration/validate-packages-in-manifest/deployment.yaml
  ./tests/src/integration/validate-packages-in-manifest/manifest.yaml
  ./tests/src/integration/validatePackageInDeployment/deployment.yaml
  ./tests/src/integration/validatePackageInDeployment/manifest.yaml
  ./tests/src/integration/validatePackageInDeployment/actions/helloworld.js
  ./tests/src/integration/validatePackagesInDeployment/deployment.yaml
  ./tests/src/integration/validatePackagesInDeployment/manifest.yaml
  ./tests/src/integration/validatePackagesInDeployment/actions/helloworld.js
  ./tests/src/integration/validateSequencesCreation/actions/function.js
  ./tests/src/integration/webaction/manifest.yml
  ./tests/src/integration/webaction/src/greeting.js
  ./tests/src/integration/zipaction/deployment.yml
  ./tests/src/integration/zipaction/manifest.yml
  ./tests/src/integration/zipaction/actions/cat/index.js
  ./tests/src/integration/zipaction/actions/cat/node_modules/cat/README.md
  ./tests/src/integration/zipaction/actions/cat/node_modules/cat/bin.js
  ./tests/src/integration/zipaction/actions/cat/node_modules/cat/example.js
  ./tests/src/integration/zipaction/actions/cat/node_modules/cat/index.js
  ./tests/usecases/api-gateway/simple_api_manifest.yaml
  ./tests/usecases/api-gateway/actions/fire/index.js
  ./tests/usecases/badyaml/deployment.yaml
  ./tests/usecases/badyaml/manifest.yaml
  ./tests/usecases/dependency/README.md
  ./tests/usecases/dependency/manifest.yaml
  ./tests/usecases/github/README.md
  ./tests/usecases/github/deployment.yaml
  ./tests/usecases/github/manifest.yaml
  ./tests/usecases/github/src/print-github-commits.js
  ./tests/usecases/slack/README.md
  ./tests/usecases/slack/deployment.yaml
  ./tests/usecases/slack/manifest.yaml
  ./tests/usecases/slack/actions/post-to-slack.js
  ./tests/usecases/triggerrule/README.md
  ./tests/usecases/triggerrule/deployment.yml
  ./tests/usecases/triggerrule/manifest.yml
  ./tests/usecases/triggerrule/src/greeting.js
  ./tools/travis/build_tag_releases.sh
  ./tools/travis/cloneutils.sh
  ./tools/travis/scancode.sh
  ./tools/travis/script.sh
  ./tools/travis/docker/Dockerfile
  ./tools/travis/docker/publish.sh
  ./wski18n/README.md
```

**Comment by mrutkows** [comment]
@daisy-ycguo  
So other Apache projects have ASF headers for:
- .md
- .yaml (config files)

but what about the following types? Is there a precedent (example) in other projects for:
- Dockerfile
- Makefile
- hosts (file)
- travis.yml
- .sh (Bash)
- .wskprops (any file with a leading "." dot)

If so, can you confirm and link at least 1 example that ASF approved as part of another release?

**Comment by michaelmarth** [comment]
@bdelacretaz do you happen to have input on  the above?

**Comment by daisy-ycguo** [comment]
@mrutkows Please refer to [.rat-excludes](https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/.rat-excludes). Only below files are excluded from adding license headers.

```
# files copied from third parties or created by tools
gradlew
gradlew.bat
Godeps
i18n_resources.go

# JSON data file doesn't support annotation
.*json

# Test data 

# others
.gitignore
.rat-excludes
```

**Comment by daisy-ycguo** [comment]
@mrutkows Thank you for merging PR #709. This issue has been fixed. Now wskdeploy can pass the license header audit by running Apache Rat.

**Comment by daisy-ycguo** [comment]
More files:
```
  openwhisk-wskdeploy/tests/src/integration/apigateway/src/list-members.js
  openwhisk-wskdeploy/tests/src/integration/apigateway/src/get-books.js
  openwhisk-wskdeploy/tests/src/integration/apigateway/src/put-books.js
  openwhisk-wskdeploy/tests/src/integration/apigateway/src/delete-books.js
  openwhisk-wskdeploy/tests/src/integration/apigateway/src/post-books.js
```

**Comment by mrutkows** [comment]
@daisy-ycguo i just submitted PR[882](https://github.com/apache/incubator-openwhisk-wskdeploy/pull/882)  to add headers to the .js files listed above for the API Gateway integration test.

**Comment by mrutkows** [comment]
@daisy-ycguo which files are still missing ASF license headers (or not documented as exclusions)?

**Comment by daisy-ycguo** [comment]
No. This repo is all good. We can close this issue.
